// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASxXCQj-HZZoZH5-KfQ6MR4sdc3P50bKU',
    appId: '1:752792676495:web:d4c0ba76d8bb0b41de68fa',
    messagingSenderId: '752792676495',
    projectId: 'spacenews-core-ea1de',
    authDomain: 'spacenews-core-ea1de.firebaseapp.com',
    storageBucket: 'spacenews-core-ea1de.firebasestorage.app',
    measurementId: 'G-NY9JJ7Z63K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLe2M8-GD5oUUFtEPKCxzCaNYSr0qZFNE',
    appId: '1:752792676495:android:d2e3687a561685bcde68fa',
    messagingSenderId: '752792676495',
    projectId: 'spacenews-core-ea1de',
    storageBucket: 'spacenews-core-ea1de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaO2aYQZosefXE5-1Y30YcDWw1l0-voA',
    appId: '1:752792676495:ios:8f853af212e826cfde68fa',
    messagingSenderId: '752792676495',
    projectId: 'spacenews-core-ea1de',
    storageBucket: 'spacenews-core-ea1de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaO2aYQZosefXE5-1Y30YcDWw1l0-voA',
    appId: '1:752792676495:ios:8f853af212e826cfde68fa',
    messagingSenderId: '752792676495',
    projectId: 'spacenews-core-ea1de',
    storageBucket: 'spacenews-core-ea1de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASxXCQj-HZZoZH5-KfQ6MR4sdc3P50bKU',
    appId: '1:752792676495:web:7472c633fe1b1ea8de68fa',
    messagingSenderId: '752792676495',
    projectId: 'spacenews-core-ea1de',
    authDomain: 'spacenews-core-ea1de.firebaseapp.com',
    storageBucket: 'spacenews-core-ea1de.firebasestorage.app',
    measurementId: 'G-2MYH782HBG',
  );
}
